namespace Engineering.Application.Services.FiduciaryProductManages.Models.UpdateFiduciaryProductDetailReturn;

public record UpdateFiduciaryProductDetailReturnResponse(long FiduciaryProductDetailReturnId);
