namespace Engineering.Application.Services.ContractorStatusStatements.Contracts.GetsContractorStatusStatementDailyExcel.Enum;

public record GetContractorStatusStatementDailyServiceExcelEnumRequest(
) : IHttpRequest;