namespace Engineering.Application.Services.DailyProjectOperations.Models.GetFilteredMachineries;

public record GetFilteredMachineriesResponse(List<GetFilteredMachineriesResponseModel> Data, int RowCount);