namespace Engineering.Application.Services.ProjectOperationDetailSchedulings.Models.GetProjectOperationDetailSchedulingTypes;

public record GetProjectOperationDetailSchedulingTypeResponse(List<EnumObject> Data);
