namespace Engineering.Application.Services.ProjectOperationDetailSchedulings.Models.GetProjectOperationDetailSchedulingTypes;

public record GetProjectOperationDetailSchedulingTypeRequest() : IHttpRequest;
