
namespace Engineering.Application.Services.ContractorContracts.Queries.GetsPartialProjectOperationDetailService;

public class GetsPartialProjectOperationDetailServiceQueryValidator : AbstractValidator<GetsPartialProjectOperationDetailServiceQuery>
{
}
