namespace Engineering.Application.Services.DailyProjectOperations.Models.GetFilteredConsumableExperts;

public record GetFilteredConsumableExpertsResponse(List<GetFilteredConsumableExpertsModel> Data, int RowCount);