namespace Engineering.Application.Services.DailyProjectOperations.Models.GetsDailyProjectOperationServiceExcelExporter;

public record GetsDailyProjectOperationServiceExcelExporterResponse(FileContentResult File);

