namespace Engineering.Application.Services.TelegramChats.Models.CommerceRequestWarehouseStatusChangeTelegramMessage;

public record CommerceRequestWarehouseStatusChangeTelegramMessageResponse(bool IsDone);