namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.GetTotalDailiesByProjectOperationDetailId;

public record GetTotalDailiesByProjectOperationDetailIdRequest(long ProjectOperationDetailId, bool? IncpectionRead) : IHttpRequest;
