
namespace Engineering.Application.Services.ContractorContracts.Queries.GetsRequestedOperationContract;

public class GetsRequestedOperationContractQueryValidator : AbstractValidator<GetsRequestedOperationContractQuery>
{
}
