namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.UpdateProjectOperationTemporaryDaily;

public record UpdateProjectOperationTemporaryDailyResponse(long ProjectOperationTemporaryDailyId);
