namespace Engineering.Application.Services.FiduciaryProductManages.Models.GetFiduciaryProductDetailReturnByDetailId;

public record GetFiduciaryProductDetailReturnByDetailIdRequest(long FiduciaryProductDetailId) : IHttpRequest;
