namespace Engineering.Application.Services.ProjectOperationDetails.Models.CreateProjectOperationDetailComment;

public record CreateProjectOperationDetailCommentResponse(long ProjectOperationDetailCommentId);
