namespace Engineering.Application.Services.EmployerStatusStatements.Models.GetsEmployerStatusStatementProjectOperationExcelEnum;

public record GetsEmployerStatusStatementProjectOperationExcelEnumsRequest() : IHttpRequest;
