namespace Engineering.Application.Services.EmployerStatusStatements.Models.GetsEmployerStatusStatementProjectOperationExcelEnum;

public record GetsEmployerStatusStatementProjectOperationExcelEnumsResponse(List<EnumObject> Data);