namespace Engineering.Application.Services.ProjectOperationDetailSchedulings.Models.GetSchedulingProjectOperationDetails;

public record GetSchedulingOperationLocationsResponse(List<GetSchedulingOperationLocationsResponseModel> Data, int RowCount);
