namespace Engineering.Application.Services.RequestMachineryManagements.Models.ActiveRequestMachineryInquiryOperator;

public record ActiveRequestMachineryInquiryOperatorResponse(long RequestMachineryInquiryOperatorId);
