namespace Engineering.Application.Services.RequestMachineryManagements.Models.SetRequestMachineryOperatorAppointment;

public record SetRequestMachineryOperatorAppointmentResponse(long RequestMachineryId);
