namespace Engineering.Application.Services.RequestContractorInquiries.Models.UpdateRequestContractorInquiry;

public record UpdateRequestContractorInquiryResponse(long RequestContractorInquiyId, bool IsUpdated);
