namespace Engineering.Application.Services.EmployerStatusStatements.Models.GetEmployerStatusStatementExcelExporter;

public record GetEmployerStatusStatementExcelExporterResponse(FileContentResult File);

