namespace Engineering.Application.Services.RequestMachineryManagements.Models.GetFilteredRequestMachineryInquieries;

public record GetFilteredRequestMachineryInquieriesResponse(List<GetFilteredRequestMachineryInquieriesModel> Data, int RowCount);
