namespace Engineering.Application.Services.TelegramChats.Models.EntryThroughRelocationForTemporaryDeliveryTelegramMessage;

public record EntryThroughRelocationForTemporaryDeliveryTelegramMessageResponse(bool IsDone);