<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Gita.Backend.Shared.Application" Version="2.2.244" />
		<PackageReference Include="IdentityServer.ClientSdk" Version="1.2.460" />
	</ItemGroup>

</Project>
