using Engineering.Domain.Entities.RequestMachineries;

namespace Engineering.Application.Services.RequestMachineries.Commands.DeleteRequestMachineryProjectOperationDetail;

public record DeleteRequestMachineryProjectOperationDetailCommand(long RequestMachineryProjectOperationDetailId) : ICommand<RequestMachineryProjectOperationDetail>;
