namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.DeleteProjectOperationTemporaryDaily;

public record DeleteProjectOperationTemporaryDailyResponse(long ProjectOperationTemporaryDailyId);
