namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.DeleteProjectOperationTemporaryDaily;

public record DeleteProjectOperationTemporaryDailyRequest(long Id) : IHttpRequest;
