namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.CreateProjectOperationDetailInspection;

public record CreateProjectOperationDetailInspectionResponse(long ProjectOperationDetailInspectionId);
