namespace Engineering.Application.Services.CostCenterVirtualGroups.Models.DeleteCostCenterVirtualGroup;

public record DeleteCostCenterVirtualGroupRequest(long CostCenterVirtualGroupId) : IHttpRequest;
