namespace Engineering.Application.Services.RequestContractors.Models.GetFilteredRequestContractors;

public record GetFilteredRequestContractorsResponse(List<GetFilteredRequestContractorsModel> Data, int RowCount);
