using Engineering.Application.Services.RequestMachineryStatusStatements.Models.CreateRequestMachineryStatusStatement;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetFilteredRequestMachineryStatusStatement;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementById;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementStatus;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementUnit;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetsRequestMachineryStatusStatementExcelEnum;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetsRequestMachineryStatusStatementExcelExporter;
using Engineering.Application.Services.RequestMachineryStatusStatements.Models.RequestMachineryStatusStatementStatusChanger;

namespace Engineering.Application.Services.RequestMachineryStatusStatements;

public interface IRequestMachineryStatusStatementLogic
{
    Task<Result<CreateRequestMachineryStatusStatementResponse?>> CreateRequestMachineryStatusStatement(CreateRequestMachineryStatusStatementRequest request, CT ct);
    Task<Result<RequestMachineryStatusStatementStatusChangerResponse?>> RequestMachineryStatusStatementStatusChanger(RequestMachineryStatusStatementStatusChangerRequest request, CT ct);
    Task<Result<GetRequestMachineryStatusStatementByIdResponse?>> GetRequestMachineryStatusStatementById(GetRequestMachineryStatusStatementByIdRequest request, CT ct);
    Task<Result<GetRequestMachineryStatusStatementStatusResponse?>> GetRequestMachineryStatusStatementStatus(GetRequestMachineryStatusStatementStatusRequest request, CT ct);
    Task<Result<GetRequestMachineryStatusStatementUnitResponse?>> GetRequestMachineryStatusStatementUnit(GetRequestMachineryStatusStatementUnitRequest request, CT ct);
    Task<Result<GetFilteredRequestMachineryStatusStatementResponse?>> GetFilteredRequestMachineryStatusStatement(GetFilteredRequestMachineryStatusStatementRequest request, CT ct);
    Task<Result<GetsRequestMachineryStatusStatementExcelEnumResponse?>> GetsRequestMachineryStatusStatementExcelEnum(GetsRequestMachineryStatusStatementExcelEnumRequest request, CT ct);
    Task<Result<GetsRequestMachineryStatusStatementExcelExporterResponse?>> GetsRequestMachineryStatusStatementExcelExporter(GetsRequestMachineryStatusStatementExcelExporterRequest request, CT ct);
}
