namespace Engineering.Application.Services.FiduciaryProducts.Models.GetFilteredFiduciaryProductsExcelExporter;

public record GetFilteredFiduciaryProductsExcelExporterResponse(FileContentResult File);

