namespace Engineering.Application.Services.RequestMachineryManagements.Models.SetRequestMachineryBackToOnProject;

public record SetRequestMachineryBackToOnProjectResponse(List<long> RequestMachineryIds, bool UpdateState);
