namespace Engineering.Application.Services.FiduciaryProductManages.Models.CreateFiduciaryProductDetailReturn;

public record CreateFiduciaryProductDetailReturnRequest(List<CreateFiduciaryProductDetailReturnModelRequest> Data) : IHttpRequest;
