namespace Engineering.Application.Services.CostCenterVirtualGroups.Models.UpdateCostCenterVirtualGroupAdmin;

public record UpdateCostCenterVirtualGroupAdminResponse(long CostCenterVirtualGroupAdminId);
