namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.GetProjectOperationDetailInspectionById;

public record GetProjectOperationDetailInspectionByIdRequest(long Id) : IHttpRequest;
