namespace Engineering.Application.Services.RequestMachineryManagements.Models.SetRequestMachineryManagerConfirm;

public record SetRequestMachineryManagerConfirmResponse(List<long> RequestMachineryIds, bool UpdateState);
