namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.UpdateProjectOperationDetailInspection;

public record UpdateProjectOperationDetailInspectionResponse(long ProjectOperationDetailInspectionId);
