using Engineering.Domain.Entities.CostCenters;

namespace Engineering.Application.Services.CostCenterVirtualGroups.Commands.DeleteCostCenterVirtualGroupAdmin;

public record DeleteCostCenterVirtualGroupAdminCommand(long CostCenterVirtualGroupAdminId) : ICommand<CostCenterVirtualGroupAdmin>;
