namespace Engineering.Application.Services.FiduciaryProductManages.Models.DeleteFiduciaryProductDetailReturn;

public record DeleteFiduciaryProductDetailReturnRequest(long FiduciaryProductDetailReturnId) : IHttpRequest;
