namespace Engineering.Application.Services.FiduciaryProductManages.Models.DeleteFiduciaryProductDetailReturn;

public record DeleteFiduciaryProductDetailReturnResponse(long FiduciaryProductDetailReturnId);
