using Engineering.Application.Services.RequestContractors.Models.GetRequestContractorInquiryById;

namespace Engineering.Application.Services.RequestContractorInquiries.Queries.GetRequestContractorInquiryModelById;

public record GetRequestContractorInquiryModelByIdQuery(long RequestContractorInquiryId) : IQuery<GetRequestContractorInquiryByIdResponse>;
