namespace Engineering.Application.Services.RequestMachineryManagements.Models.InActiveRequestMachineryInquiryOperator;

public record InActiveRequestMachineryInquiryOperatorResponse(long RequestMachineryInquiryOperatorId);
