namespace Engineering.Application.Services.CostCenterVirtualGroups.Models.DeleteCostCenterVirtualGroupAdmin;

public record DeleteCostCenterVirtualGroupAdminResponse(long CostCenterVirtualGroupAdminId);
