namespace Engineering.Application.Services.CostCenterVirtualGroups.Models.DeleteCostCenterVirtualGroupAdmin;

public record DeleteCostCenterVirtualGroupAdminRequest(long CostCenterVirtualGroupAdminId) : IHttpRequest;