namespace Engineering.Application.Services.RequestMachineryManagements.Models.GetRequestMachineryInquiries;

public record GetRequestMachineryInquiriesRequest(long RequestMachineryId) : IHttpRequest;
