using Engineering.Domain.Entities.ProjectOperations;

namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Commands.DeleteProjectOperationTemporaryDaily;

public record DeleteProjectOperationTemporaryDailyCommand(long ProjectOperationTemporaryDailyId) : ICommand<ProjectOperationTemporaryDaily>;
