namespace Engineering.Application.Services.DailyProjectOperations.Models.GetsDetailedDailyProjectOperationExcelExporter;

public record GetsDetailedDailyProjectOperationExcelExporterResponse(FileContentResult File);

