namespace Engineering.Application.Services.FiduciaryProducts.Models.GetFilteredFiduciaryProductHistories;

public record GetFilteredFiduciaryProductHistoriesDetail(List<GetFilteredFiduciaryProductHistoriesModel> Data, int RowCount);
