namespace Engineering.Application.Services.FiduciaryProducts.Models.GetFilteredFiduciaryProductHistories;

public record GetFilteredFiduciaryProductHistoriesResponse(List<GetFilteredFiduciaryProductHistoriesModel> Data, int RowCount);