namespace Engineering.Application.Services.RequestContractorInquiries.Models.GetRequestContractorInquiryByRequestId;

public record GetRequestContractorInquiryByRequestIdResponse(List<GetRequestContractorInquiryByRequestIdModel> Data, int RowCount);
