
namespace Engineering.Application.Services.ContractorContracts.Queries.GetsIntegratedProjectOperationDetailService;

public class GetsIntegratedProjectOperationDetailServiceQueryValidator : AbstractValidator<GetsIntegratedProjectOperationDetailServiceQuery>
{
}
