
namespace Engineering.Application.Services.ContractorContracts.Queries.GetsContractorServiceFiltered;

public class GetsContractorServiceFilteredQueryValidator : AbstractValidator<GetsContractorServiceFilteredQuery>
{
}
