namespace Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementUnit;

public record GetRequestMachineryStatusStatementUnitResponse(List<EnumObject> Data);
