

namespace Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementUnit;

public record GetRequestMachineryStatusStatementUnitRequest() : IHttpRequest;
