namespace Engineering.Application.Services.RequestMachineryManagements.Models.GetFilteredRequestMachineryManagements;

public record GetFilteredRequestMachineryManagementsResponse(List<GetFilteredRequestMachineryManagementsModel> Data, int RowCount);
