namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.GetProjectOperationTemporaryDailyById;

public record GetProjectOperationTemporaryDailyByIdRequest(long Id) : IHttpRequest;
