namespace Engineering.Application.Services.ProjectOperationDetails.Models.GetsByProjectOperationIdExcelExporter;

public record GetsByProjectOperationIdExcelExporterResponse(FileContentResult File);

