namespace Engineering.Application.Services.ProjectOperationDetailSchedulings.Models.GetSchedulingProjectOperations;

public record GetSchedulingOperationInfosResponse(List<GetSchedulingOperationInfosResponseModel> Data, int RowCount);
