namespace Engineering.Application.Services.TransportationRequests.Models.CreateAirplane;

public record CreateAirplaneRequest(
    List<long> CostCenterIds,
    List<long>? ProjectIds,
    long TripId,
    long StartingCityId,
    long DestinationCityId,
    DateTime StartDate,
    DateTime EndDate,
    TimeSpan? StartTime,
    TimeSpan? EndTime,
    string? Description,
    List<long>? ProjectOperationIds,
    List<long>? ProjectOperationDetailIds,
    string? AccountName,
    string? AccountNumber,
    long? BankId,
    long? TicketPayerId,
    string? CardNumber,
    long? CurrencyUnitId,
    long? TransportationCostGroupId,
    long? TransportationCostCategoryId,
    long? PassengerId,
    string? Passenger,
    decimal? FareAmount,
    string? DestinationAddress,
    string? IBAN,
    List<string>? DocumentUrls
     ) : IHttpRequest;
