namespace Engineering.Application.Services.ProjectOperations.Models.GetsProjectOperationDailyReportingExcelExporter;

public record GetsProjectOperationDailyReportingExcelExporterResponse(FileContentResult File);