namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.GetProjectOperationTemporaryDailyStatus;

public record GetProjectOperationTemporaryDailyStatusRequest() : IHttpRequest;
