namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.GetProjectOperationTemporaryDailyStatus;

public record GetProjectOperationTemporaryDailyStatusResponse(List<EnumObject> Data);
