using Engineering.Domain.Entities.RequestContractors;

namespace Engineering.Application.Services.RequestContractorInquiries.Commands.DeleteRequestContractorInquiry;

public record DeleteRequestContractorInquiryCommand(RequestContractorInquiry RequestContractorInquiry) : ICommand<RequestContractorInquiry>;
