using Engineering.Domain.Entities.RequestMachineries;

namespace Engineering.Application.Services.RequestMachineries.Commands.SetOnProjectRequestMachineryConfirmDate;

public record SetOnProjectRequestMachineryConfirmDateCommand(RequestMachinery RequestMachinery) : ICommand<RequestMachinery>;
