namespace Engineering.Application.Services.ProjectOperationTemporaryDailies.Models.CreateProjectOperationTemporaryDaily;

public record CreateProjectOperationTemporaryDailyResponse(long ProjectOperationTemporaryDailyId);
