namespace Engineering.Application.Services.ProjectOperations.Models.GetsProjectOperationDailyReportingExcelEnum;

public record GetsProjectOperationDailyReportingExcelEnumResponse(List<EnumObject> Data);