namespace Engineering.Application.Services.FiduciaryProductManages.Models.GetFiduciaryProductDetailReturnDocumentById;

public record GetFiduciaryProductDetailReturnDocumentByIdResponse(List<string> Urls, int RowCount);
