namespace Engineering.Application.Services.RequestContractors.Models.GetRequestContractorInquiryById;

public record GetRequestContractorInquiryByIdRequest(long RequestContractorInquiryId) : IHttpRequest;
