namespace Engineering.Application.Services.RequestMachineryManagements.Models.SetRequestMachineryInquiryAppointment;

public record SetRequestMachineryInquiryAppointmentResponse(long RequestMachineryId);
