namespace Engineering.Application.Services.DailyProjectOperations.Models.GetDailyProjectOperationHistories;

public record GetDailyProjectOperationHistoriesModel(List<GetDailyProjectOperationHistoriesDetailModel> Data, int RowCount);
