
namespace Engineering.Application.Services.FiduciaryProductManages.Models.GetFiduciaryProductDetailManagementStatus;

public record GetFiduciaryProductDetailManagementStatusResponse(List<EnumObject> Data);
