namespace Engineering.Application.Services.ContractorStatusStatements.Models.GetContractorStatusStatementDailyServiceExcelExporter;

public record GetContractorStatusStatementDailyServiceExcelExporterResponse(
    FileContentResult File
);