<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Polly.Core" Version="8.6.6" />
		<PackageReference Include="Polly.Extensions" Version="8.6.6" />
		<PackageReference Include="Gita.Backend.Shared.Infra" Version="2.2.244" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Engineering.Application\Engineering.Application.csproj" />
	</ItemGroup>

</Project>
