namespace Engineering.Application.Services.RequestMachineryManagements.Models.SetRequestMachinerySendToManager;

public record SetRequestMachinerySendToManagerResponse(List<long> RequestMachineryIds, bool UpdateState);
