namespace Engineering.Application.Services.ContractorContracts.Contracts.GetsContractorContractDetailCooperationBasis;

public record GetsContractorContractDetailCooperationBasisRequest() : IHttpRequest;
