namespace Engineering.Application.Services.ContractorContracts.Contracts.GetsContractorContractDetailCooperationBasis;

public record GetsContractorContractDetailCooperationBasisResponse(List<EnumObject> Data);
