namespace Engineering.Application.Services.TelegramChats.Models.ExitRelocationForTemporaryDeliveryTelegramMessage;

public record ExitRelocationForTemporaryDeliveryTelegramMessageResponse(bool IsDone);