namespace Engineering.Application.WebServices.Commercial.Commerces.Models.CreateCommerce;

public record CreateCommerceRequestProcessRequest(
    long? Id,
    int Type,
    long? CostCenterId,
    long? ProjectId,
    long? ProjectOperationId,
    List<long>? ProjectOperationDetailIds,
    long ProductId,
    decimal RequestCount,
    decimal? Price,
    long? CurrencyId,
    string? Description,
    DateTime? DeliveryDate,
    long? OperatorAppointmentId,
    long? OwnerId,
    long? CommercialRequestId,
    string? CommercialRequestNumber,
    CreateCommerceRequestRequestInquieyModel? Inquiry,
    List<CreateCommerceRequestRequestDocument>? Documents,
    bool CreateInvoice,
    bool IsManually,
    long? PackageId,
    long? DestinationWarehouseId,
    bool? CheckGroup,
    string? LagecyId,
    string? ProductDescription,
    string? AdminDescription,
    long? SupplyerId,
    long? RequestConfirmUserId,
    string? FactorNumber,
    long? CategoryId,
    long? BranchId,
    long? SeasonId,
    long? BuyerId,
    DateTime? RequestedDate,
    DateTime? Created
    );

public record CreateCommerceRequest(
    long? Id,
    int Type,
    long? CostCenterId,
    long? ProjectId,
    long? ProjectOperationId,
    List<long>? ProjectOperationDetailIds,
    long ProductId,
    decimal RequestCount,
    decimal? Price,
    long? CurrencyId,
    string? Description,
    DateTime? DeliveryDate,
    long? OperatorAppointmentId,
    long? OwnerId,
    long? RequestGoodsSupplyId,
    long? CommercialRequestId,
    string? CommercialRequestNumber,
    CreateCommerceRequestRequestInquieyModel? Inquiry,
    List<CreateCommerceRequestRequestDocument>? Documents,
    bool CreateInvoice,
    bool IsManually,
    long? PackageId,
    long? DestinationWarehouseId,
    bool? CheckGroup,
    string? LagecyId,
    string? ProductDescription,
    string? AdminDescription,
    long? SupplyerId,
    long? RequestConfirmUserId,
    string? FactorNumber,
    long? CategoryId,
    long? BranchId,
    long? SeasonId,
    long? BuyerId,
    DateTime? RequestedDate,
    DateTime? Created,
    string? RequestSerialNumber
    );

public record CreateCommerceRequestRequestInquieyModel(
    long? Id,
    long? ThirdPartyId,
    long? CurrencyId,
    decimal? TaxPrice,
    decimal? PackingPrice,
    decimal? TransferPrice,
    decimal? OtherPrice,
    List<CreateCommerceRequestRequestModel>? Details
    );

public record CreateCommerceRequestRequestModel(
    long? Id,
    long? PackageId,
    decimal RequestCount,
    decimal? Price,
    decimal? OriginalPrice,
    decimal? DiscountedPrice,
    decimal? FinalPrice,
    decimal? Discount,
    decimal? DiscountPercent,
    decimal? ProductPrice,
    bool IsDeleted);

public record CreateCommerceRequestRequestDocument(
    long? Id,
    string Url,
    bool IsDeleted
    );
