namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.DeleteProjectOperationDetailInspection;

public record DeleteProjectOperationDetailInspectionResponse(long ProjectOperationDetailInspectionId);
