namespace Engineering.Application.Services.ProjectOperationDetailInspections.Models.DeleteProjectOperationDetailInspection;

public record DeleteProjectOperationDetailInspectionRequest(long Id) : IHttpRequest;
