namespace Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementStatus;

public record GetRequestMachineryStatusStatementStatusResponse(List<EnumObject> Data);
