

namespace Engineering.Application.Services.RequestMachineryStatusStatements.Models.GetRequestMachineryStatusStatementStatus;

public record GetRequestMachineryStatusStatementStatusRequest() : IHttpRequest;
