namespace Engineering.Application.Services.RequestMachineries.Models.GetRequestMachineryMachineries;

public record GetRequestMachineryMachineriesResponse(List<GetRequestMachineryMachineriesModel> Data, int RowCount);
