namespace Engineering.Application.Services.ProjectOperationDetails.Models.DeleteProjectOperationDetailComment;

public record DeleteProjectOperationDetailCommentResponse(long ProjectOperationDetailCommentId);
