namespace Engineering.Application.Services.RequestMachineries.Models.GetOnProjectMachineryReports;

public record GetOnProjectMachineryReportsResponse(List<GetOnProjectMachineryReportsModel> Data, int RowCount);
