namespace Engineering.Application.Services.CostCenterVirtualGroups.Models.CreateCostCenterVirtualGroupAdmin;

public record CreateCostCenterVirtualGroupAdminResponse(long CostCenterVirtualGroupAdminId);
