using System.ComponentModel;

namespace Engineering.Application.Services.RequestGoodsSupplyDetails.Models.GetRequestGoodsSupplyDetailsExcelEnums;

public enum GoodsSupplyDetailExcelEnum
{
    [Description("شناسه")] Id = 1,
    [Description("شماره درخواست")] RequestNumber = 2,
    [Description("تاریخ درخواست")] CreatedShamsi = 3,
    [Description("تعداد کالا")] ProductNumber = 4,
    [Description("گروه کالا")] GroupName = 5,
    [Description("کد گروه کالا")] GroupCode = 6,
    [Description("واحد گروه")] GroupMeasure = 7,
    [Description("نام کالا")] ProductName = 8,
    [Description("کد کالا")] ProductCode = 9,
    [Description("برند")] Brand = 10,
    [Description("مدل")] BrandModel = 11,
    [Description("موقعیت جزیی")] PrivateName = 12,
    [Description("کد موقعیت جزیی")] PrivateCode = 13,
    [Description("موقعیت")] PublicName = 14,
    [Description("کد موقعیت")] PublicCode = 15,
    [Description("توضیحات ریزمتره")] ProjectOperationDetailDescription = 16,
    [Description("مرکز هزینه")] CostCenter = 17,
    [Description("پروژه")] Project = 18,
    [Description("شرح عملیات")] ProjectOperation = 19,
    [Description("درصد تلورانس")] TolerancePercentage = 20,
    [Description("تعداد تلورانس")] ToleranceCount = 21,
    [Description("مقدار کل برآورد")] TotalEstimatedCount = 22,
    [Description("تعداد کل درخواست")] TotalRequestedCount = 23,
    [Description("تعداد کل تامین شده")] TotalSupplyCount = 24,
    [Description("تعداد کل باقی مانده")] TotalRemainedCount = 25,
    [Description("تعداد درخواست")] RequestedCount = 26,
    [Description("تعداد تامین شده")] SupplyCount = 27,
    [Description("تعداد باقی مانده")] RemainedCount = 28,
    [Description("تاریخ تحویل")] DelivaryDeadLine = 29,
    [Description("ارز")] Currency = 30,
    [Description("وضعیت کالا")] StatusDescription = 31,
    [Description("نوع درخواست")] RequestTypeDescription = 32,
    [Description("درخواست دهنده")] Creator = 33,
    [Description("توضیحات")] Description = 34,
    [Description("توضیحات کارشناس ارشد")] ManagementDescription = 35,
    [Description("انبار مقصد")] DestinationWarehouse = 36,
    [Description("پیمانکار")] Contractor = 37,
    [Description("نام مستعار پیمانکار")] NickName = 38,
    [Description("شماره فاکتور کالا")] CustomerInvoiceNumber = 39,
    [Description("گنجایش بسته بندی")] Quantity = 40,
    [Description("عنوان بسته بندی")] Title = 41,
    [Description("تعداد بسته بندی")] PackageCount = 42,
    [Description("تامین کننده")] Supplier = 43,
    [Description("آخرین توضیحات")] LastDescription = 44,
}