namespace Engineering.Application.Services.RequestMachineryManagements.Models.UpdateRequestMachineryAssignments;

public record UpdateRequestMachineryAssignmentsResponse(long RequestMachineryId, bool IsUpdated);
